name: quran_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  animate_do: ^3.0.2
  audioplayers: ^5.0.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Quran.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/adhkar_audio/
    - assets/quran_audio/001/
    - assets/quran_audio/002/
    - assets/quran_audio/003/
    - assets/quran_audio/004/
    - assets/quran_audio/005/
    - assets/quran_audio/006/
    - assets/quran_audio/007/
    - assets/quran_audio/008/
    - assets/quran_audio/009/
    - assets/quran_audio/010/
    - assets/quran_audio/011/
    - assets/quran_audio/012/
    - assets/quran_audio/013/
    - assets/quran_audio/014/
    - assets/quran_audio/015/
    - assets/quran_audio/016/
    - assets/quran_audio/017/
    - assets/quran_audio/018/
    - assets/quran_audio/019/
    - assets/quran_audio/020/
    - assets/quran_audio/021/
    - assets/quran_audio/022/
    - assets/quran_audio/023/
    - assets/quran_audio/024/
    - assets/quran_audio/025/
    - assets/quran_audio/026/
    - assets/quran_audio/027/
    - assets/quran_audio/028/
    - assets/quran_audio/029/
    - assets/quran_audio/030/
    - assets/quran_audio/031/
    - assets/quran_audio/032/
    - assets/quran_audio/033/
    - assets/quran_audio/034/
    - assets/quran_audio/035/
    - assets/quran_audio/036/
    - assets/quran_audio/037/
    - assets/quran_audio/038/
    - assets/quran_audio/039/
    - assets/quran_audio/040/
    - assets/quran_audio/041/
    - assets/quran_audio/042/
    - assets/quran_audio/043/
    - assets/quran_audio/044/
    - assets/quran_audio/045/
    - assets/quran_audio/046/
    - assets/quran_audio/047/
    - assets/quran_audio/048/
    - assets/quran_audio/049/
    - assets/quran_audio/050/
    - assets/quran_audio/051/
    - assets/quran_audio/052/
    - assets/quran_audio/053/
    - assets/quran_audio/054/
    - assets/quran_audio/055/
    - assets/quran_audio/056/
    - assets/quran_audio/057/
    - assets/quran_audio/058/
    - assets/quran_audio/059/
    - assets/quran_audio/060/
    - assets/quran_audio/061/
    - assets/quran_audio/062/
    - assets/quran_audio/063/
    - assets/quran_audio/064/
    - assets/quran_audio/065/
    - assets/quran_audio/066/
    - assets/quran_audio/067/
    - assets/quran_audio/068/
    - assets/quran_audio/069/
    - assets/quran_audio/070/
    - assets/quran_audio/071/
    - assets/quran_audio/072/
    - assets/quran_audio/073/
    - assets/quran_audio/074/
    - assets/quran_audio/075/
    - assets/quran_audio/076/
    - assets/quran_audio/077/
    - assets/quran_audio/078/
    - assets/quran_audio/079/
    - assets/quran_audio/080/
    - assets/quran_audio/081/
    - assets/quran_audio/082/
    - assets/quran_audio/083/
    - assets/quran_audio/084/
    - assets/quran_audio/085/
    - assets/quran_audio/086/
    - assets/quran_audio/087/
    - assets/quran_audio/088/
    - assets/quran_audio/089/
    - assets/quran_audio/090/
    - assets/quran_audio/091/
    - assets/quran_audio/092/
    - assets/quran_audio/093/
    - assets/quran_audio/094/
    - assets/quran_audio/095/
    - assets/quran_audio/096/
    - assets/quran_audio/097/
    - assets/quran_audio/098/
    - assets/quran_audio/099/
    - assets/quran_audio/100/
    - assets/quran_audio/101/
    - assets/quran_audio/102/
    - assets/quran_audio/103/
    - assets/quran_audio/104/
    - assets/quran_audio/105/
    - assets/quran_audio/106/
    - assets/quran_audio/107/
    - assets/quran_audio/108/
    - assets/quran_audio/109/
    - assets/quran_audio/110/
    - assets/quran_audio/111/
    - assets/quran_audio/112/
    - assets/quran_audio/113/
    - assets/quran_audio/114/
